package model

// Code generated by scripts/gen_feature_types.py from packages/contracts/feature-catalog.json.
// DO NOT EDIT BY HAND (R42.2: feature-catalog.json is the single source of truth).

// Feature 功能 key 常量（规则 R42.2）。
const (
	FeatureArchiveRead = "archive.read"
	FeatureArchiveIngest = "archive.ingest"
	FeatureMediaUploadImage = "media.upload.image"
	FeatureMediaUploadVideo = "media.upload.video"
	FeatureMediaUploadAudio = "media.upload.audio"
	FeatureMediaUploadFile = "media.upload.file"
	FeatureMediaPreview = "media.preview"
	FeatureMediaTranscode = "media.transcode"
	FeatureMediaOcr = "media.ocr"
	FeatureMediaTranscribe = "media.transcribe"
	FeatureMediaDocumentExtract = "media.document_extract"
	FeatureCustomerManage = "customer.manage"
	FeatureAiProfile = "ai.profile"
	FeatureAiSummary = "ai.summary"
	FeatureAnalyticsAdvanced = "analytics.advanced"
	FeatureSearchAdvanced = "search.advanced"
	FeatureMcpRead = "mcp.read"
	FeatureMcpWrite = "mcp.write"
	FeatureBackupSchedule = "backup.schedule"
	FeatureEnterpriseSso = "enterprise.sso"
	FeatureDataExport = "data.export"
	FeatureQualityManage = "quality.manage"
	FeatureOpsManage = "ops.manage"
)

// FeatureDeps 功能依赖表（depends_on）。生成器保证与 feature-catalog.json 一致。
var FeatureDeps = map[string][]string{
	"media.upload.image": {"archive.ingest"} ,
	"media.upload.video": {"archive.ingest"} ,
	"media.upload.audio": {"archive.ingest"} ,
	"media.upload.file": {"archive.ingest"} ,
	"media.transcode": {"media.preview"} ,
	"ai.profile": {"customer.manage"} ,
	"mcp.write": {"mcp.read"} ,
}
