<template><section><PageHeading eyebrow="BETTER CONVERSATIONS, TOGETHER" title="群聊" description="在同一个空间里，分享各自的生活与灵感。" :count="workspace.ready&&!workspace.errors.chatrooms?items.length:null"><button class="btn" :disabled="workspace.loading" @click="refresh"><UiIcon name="refresh" :size="15"/>刷新群聊</button></PageHeading><div class="toolbar" style="padding:0 0 22px"><label class="search-field"><UiIcon name="search" :size="17"/><input v-model="query" placeholder="搜索群名称、备注或群主" aria-label="搜索群聊" type="search"/></label><span class="spacer"/><span class="count-label">{{ filtered.length }} 个群聊空间</span></div><StatePanel v-if="workspace.loading" kind="loading"/><StatePanel v-else-if="workspace.errors.chatrooms" kind="error" title="群聊暂时无法读取" :description="workspace.errors.chatrooms" @retry="refresh"/><StatePanel v-else-if="!filtered.length" :title="query?'没有匹配的群聊':'这里还没有群聊'" description="换一个关键词，或连接包含群聊的数据服务。"/><div v-else class="room-grid"><article v-for="room in paged" :key="room.id" class="room-card"><div class="room-card-top"><UiAvatar :name="room.name" group large/><button class="btn btn-ghost btn-square" :aria-label="`查看 ${room.name} 的详情`" @click="selected=room;details=true"><UiIcon name="dots" :size="17"/></button></div><div class="room-card-info"><h3>{{ room.name }}</h3><p class="truncate">群主 · {{ room.owner||'未提供' }}</p></div><div class="room-card-bottom"><span class="pill"><UiIcon name="users" :size="12"/>{{ room.members===null?'成员数未知':`${room.members} 位成员` }}</span><button class="text-button" :disabled="!room.id" @click="openChat(room)">进入档案<UiIcon name="arrow" :size="14"/></button></div></article></div><UiPager :page="page" :size="size" :total="filtered.length" :busy="workspace.loading" @change="page=$event"/><UiDialog v-model="details" :title="selected?.name||'群聊详情'" eyebrow="GROUP DETAILS"><dl v-if="selected" class="detail-list"><dt>群名称</dt><dd>{{ selected.name }}</dd><dt>群主</dt><dd>{{ selected.owner||'未提供' }}</dd><dt>成员数</dt><dd>{{ selected.members??'未提供' }}</dd><dt>群聊 ID</dt><dd class="mono">{{ selected.id }}</dd></dl><template #footer><button class="btn" @click="copyText(selected?.id)"><UiIcon name="copy" :size="14"/>复制群 ID</button><button class="btn btn-primary" :disabled="!selected?.id" @click="openChat(selected)">查看聊天记录<UiIcon name="arrow" :size="14"/></button></template></UiDialog></section></template>
<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useCollection } from '@/lib/useCollection'
import { copyText } from '@/lib/workspace'
import UiIcon from '@/components/ui/UiIcon.vue'
import UiAvatar from '@/components/ui/UiAvatar.vue'
import PageHeading from '@/components/ui/PageHeading.vue'
import UiPager from '@/components/ui/UiPager.vue'
import UiDialog from '@/components/ui/UiDialog.vue'
import StatePanel from '@/components/ui/StatePanel.vue'
export default {name:'ArchiveChatRooms',components:{UiIcon,UiAvatar,PageHeading,UiPager,UiDialog,StatePanel},setup(){const router=useRouter(),collection=useCollection('chatrooms'),details=ref(false),selected=ref(null);collection.size.value=6;return {...collection,details,selected,copyText,openChat:room=>router.push({path:'/chatlog',query:{talker:room.id}})}}}
</script>
