<template><section><PageHeading eyebrow="PEOPLE IN YOUR ARCHIVE" title="联系人" description="一个名字，就是一段故事的入口。" :count="workspace.ready&&!workspace.errors.contacts?items.length:null"><button class="btn" :disabled="workspace.loading" @click="refresh"><UiIcon name="refresh" :size="15"/>刷新联系人</button></PageHeading><div class="panel"><div class="toolbar"><label class="search-field"><UiIcon name="search" :size="17"/><input v-model="query" type="search" placeholder="搜索姓名、备注或微信号" aria-label="搜索联系人"/></label><span class="spacer"/><span class="count-label">{{ filtered.length }} 位联系人</span></div><StatePanel v-if="workspace.loading" kind="loading"/><StatePanel v-else-if="workspace.errors.contacts" kind="error" title="无法读取联系人" :description="workspace.errors.contacts" @retry="refresh"/><StatePanel v-else-if="!filtered.length" :title="query?'没有找到这个名字':'联系人档案还是空的'" description="试试其他关键词，或确认数据服务中已有联系人。"/><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>联系人</th><th>微信号 / 别名</th><th>备注</th><th>档案 ID</th><th style="text-align:right">操作</th></tr></thead><tbody><tr v-for="person in paged" :key="person.id"><td><button class="btn btn-ghost row-detail" style="padding:0;text-align:left" @click="selected=person;details=true"><UiAvatar :name="person.name"/><div><strong>{{ person.name }}</strong><small class="muted" style="display:block;margin-top:5px">{{ person.nickname||'未提供昵称' }}</small></div></button></td><td>{{ person.alias||'—' }}</td><td>{{ person.remark||'—' }}</td><td><span class="mono muted">{{ person.id||'未提供' }}</span></td><td><div class="row-actions"><button class="btn btn-ghost btn-square" :aria-label="`复制 ${person.name} 的 ID`" @click="copyText(person.id)"><UiIcon name="copy" :size="15"/></button><button class="btn" :disabled="!person.id" @click="openChat(person)">查看记录<UiIcon name="arrow" :size="13"/></button></div></td></tr></tbody></table></div><UiPager v-if="!workspace.errors.contacts" :page="page" :size="size" :total="filtered.length" :busy="workspace.loading" @change="page=$event"/></div><UiDialog v-model="details" :title="selected?.name||'联系人详情'" eyebrow="CONTACT DETAILS"><dl v-if="selected" class="detail-list"><dt>昵称</dt><dd>{{ selected.nickname||'未提供' }}</dd><dt>备注</dt><dd>{{ selected.remark||'未设置' }}</dd><dt>微信号 / 别名</dt><dd>{{ selected.alias||'未提供' }}</dd><dt>档案 ID</dt><dd class="mono">{{ selected.id||'未提供' }}</dd></dl><template #footer><button class="btn" @click="copyText(selected?.id)"><UiIcon name="copy" :size="14"/>复制 ID</button><button class="btn btn-primary" :disabled="!selected?.id" @click="openChat(selected)">查看聊天记录<UiIcon name="arrow" :size="14"/></button></template></UiDialog></section></template>
<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useCollection } from '@/lib/useCollection'
import { copyText } from '@/lib/workspace'
import UiIcon from '@/components/ui/UiIcon.vue'
import UiAvatar from '@/components/ui/UiAvatar.vue'
import PageHeading from '@/components/ui/PageHeading.vue'
import UiPager from '@/components/ui/UiPager.vue'
import UiDialog from '@/components/ui/UiDialog.vue'
import StatePanel from '@/components/ui/StatePanel.vue'
export default {name:'ArchiveContacts',components:{UiIcon,UiAvatar,PageHeading,UiPager,UiDialog,StatePanel},setup(){const router=useRouter(),details=ref(false),selected=ref(null);return {...useCollection('contacts'),details,selected,copyText,openChat:person=>router.push({path:'/chatlog',query:{talker:person.id}})}}}
</script>
