<template><section><PageHeading eyebrow="PICK UP WHERE YOU LEFT OFF" title="会话" description="所有对话，按最近发生的时间排列。" :count="workspace.ready&&!workspace.errors.sessions?items.length:null"><button class="btn" :disabled="workspace.loading" @click="refresh"><UiIcon name="refresh" :size="15"/>刷新会话</button></PageHeading><div class="panel"><div class="toolbar"><div class="segment-control" aria-label="会话类型"><button v-for="item in categories" :key="item.key" :class="{active:category===item.key}" :aria-pressed="category===item.key" @click="category=item.key">{{ item.label }}</button></div><span class="spacer"/><label class="search-field"><UiIcon name="search" :size="16"/><input v-model="query" type="search" placeholder="搜索会话名称或 ID" aria-label="搜索会话"/></label></div><StatePanel v-if="workspace.loading" kind="loading"/><StatePanel v-else-if="workspace.errors.sessions" kind="error" title="无法读取会话" :description="workspace.errors.sessions" @retry="refresh"/><StatePanel v-else-if="!rows.length" title="还没有找到对话" description="调整搜索条件，或者先连接数据服务。"/><div v-else class="session-list"><article v-for="session in rows.slice((page-1)*size,page*size)" :key="session.id" class="session-row"><button class="session-main-button" :disabled="!session.id" @click="openChat(session)"><UiAvatar :name="session.name" :group="session.kind==='room'"/><div style="min-width:0;flex:1"><h3 class="truncate">{{ session.name }}<span v-if="session.kind==='room'" class="group-pill">群聊</span></h3><p class="truncate">{{ session.preview||'打开查看聊天记录' }}</p></div></button><span class="session-time">{{ formatTime(session.lastMessageTime) }}</span><button class="btn btn-ghost btn-square" :aria-label="`复制 ${session.name} 的会话 ID`" @click="copyText(session.id)"><UiIcon name="copy" :size="14"/></button><button class="btn btn-ghost btn-square" :aria-label="`打开 ${session.name} 的聊天记录`" @click="openChat(session)"><UiIcon name="chevron" :size="17"/></button></article></div><UiPager :page="page" :size="size" :total="rows.length" :busy="workspace.loading" @change="page=$event"/></div></section></template>
<script>
import { ref,computed,watch } from 'vue'
import { useRouter } from 'vue-router'
import { useCollection } from '@/lib/useCollection'
import { copyText } from '@/lib/workspace'
import { formatTime } from '@/lib/data'
import UiIcon from '@/components/ui/UiIcon.vue'
import UiAvatar from '@/components/ui/UiAvatar.vue'
import PageHeading from '@/components/ui/PageHeading.vue'
import UiPager from '@/components/ui/UiPager.vue'
import StatePanel from '@/components/ui/StatePanel.vue'
export default {name:'ArchiveSessions',components:{UiIcon,UiAvatar,PageHeading,UiPager,StatePanel},setup(){const router=useRouter(),collection=useCollection('sessions'),category=ref('all'),categories=[{key:'all',label:'全部会话'},{key:'contact',label:'私聊'},{key:'room',label:'群聊'}],rows=computed(()=>collection.filtered.value.filter(s=>category.value==='all'||s.kind===category.value));watch(category,()=>{collection.page.value=1});return {...collection,category,categories,rows,copyText,formatTime,openChat:s=>router.push({path:'/chatlog',query:{talker:s.id}})}}}
</script>
