#!/usr/bin/env python3
"""Generate feature-catalog derived types for Go and TypeScript (R42.2).

Reads packages/contracts/feature-catalog.json (single source of truth) and
regenerates:
  - apps/server/internal/model/features.go   (feature key constants + deps)
  - apps/admin-web/src/lib/features.js       (feature constants + platform map)

Run `--check` to verify the committed files are byte-identical to the generated
output (idempotency guard). This prevents hand-maintained copies in app dirs
from drifting (R42.2: 禁止在 app 目录维护手写副本).

No product access, no signature verification. See 开发规则.md R42.2/R42.7.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "packages" / "contracts" / "feature-catalog.json"
GO_OUT = ROOT / "apps" / "server" / "internal" / "model" / "features.go"
JS_OUT = ROOT / "apps" / "admin-web" / "src" / "lib" / "features.js"


def load_catalog() -> dict:
    with CATALOG.open(encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict) or "features" not in data:
        raise ValueError("feature-catalog.json must be an object with a features array")
    return data


def _go_const_name(key: str) -> str:
    parts = []
    for part in key.replace("-", "_").split("."):
        # split on '_' too so document_extract -> DocumentExtract
        for sub in part.split("_"):
            if sub:
                parts.append(sub[:1].upper() + sub[1:])
    return "Feature" + "".join(parts)


def render_go(features: list[dict]) -> str:
    lines = [
        "package model",
        "",
        "// Code generated by scripts/gen_feature_types.py from packages/contracts/feature-catalog.json.",
        "// DO NOT EDIT BY HAND (R42.2: feature-catalog.json is the single source of truth).",
        "",
        "// Feature 功能 key 常量（规则 R42.2）。",
        "const (",
    ]
    for f in features:
        lines.append(f'\t{_go_const_name(f["key"])} = "{f["key"]}"')
    lines.append(")")
    lines.append("")
    lines.append("// FeatureDeps 功能依赖表（depends_on）。生成器保证与 feature-catalog.json 一致。")
    lines.append("var FeatureDeps = map[string][]string{")
    for f in features:
        deps = f.get("depends_on", [])
        if deps:
            dep_list = ", ".join(f'"{d}"' for d in deps)
            lines.append(f'\t"{f["key"]}": {{{dep_list}}} ,')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _js_const_name(key: str) -> str:
    return "FEATURE_" + key.replace("-", "_").replace(".", "_").upper()


def render_js(features: list[dict]) -> str:
    lines = [
        "// Code generated by scripts/gen_feature_types.py from packages/contracts/feature-catalog.json.",
        "// DO NOT EDIT BY HAND (R42.2: feature-catalog.json is the single source of truth).",
        "",
        "export const FEATURES = {",
    ]
    for f in features:
        lines.append(f'  {_js_const_name(f["key"])}: "{f["key"]}",')
    lines.append("};")
    lines.append("")
    lines.append("// 平台表单映射（R42.2）：feature key -> 平台目录展示（name/description/depends_on）。")
    lines.append("export const FEATURE_CATALOG = {")
    for f in features:
        deps = ", ".join(f'"{d}"' for d in f.get("depends_on", []))
        lines.append(f'  "{f["key"]}": {{')
        lines.append(f'    name: {json.dumps(f["name"], ensure_ascii=False)},')
        lines.append(f'    description: {json.dumps(f["description"], ensure_ascii=False)},')
        lines.append(f'    dependsOn: [{deps}],')
        lines.append("  },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify committed files match generated output")
    args = ap.parse_args()

    catalog = load_catalog()
    features = catalog["features"]

    go_text = render_go(features)
    js_text = render_js(features)

    def _read(path: Path) -> str:
        return path.read_text(encoding="utf-8") if path.exists() else ""

    go_dirty = _read(GO_OUT) != go_text
    js_dirty = _read(JS_OUT) != js_text

    if args.check:
        if go_dirty or js_dirty:
            print("FAIL: generated files out of sync with feature-catalog.json")
            if go_dirty:
                print("  - apps/server/internal/model/features.go")
            if js_dirty:
                print("  - apps/admin-web/src/lib/features.js")
            print("  Run scripts/gen_feature_types.py to regenerate.")
            return 1
        print("OK: feature types in sync with feature-catalog.json")
        return 0

    GO_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    GO_OUT.write_text(go_text, encoding="utf-8")
    JS_OUT.write_text(js_text, encoding="utf-8")
    print(f"generated {GO_OUT}")
    print(f"generated {JS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())