import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const code=await readFile(path.join(root,'src/lib/data.js'),'utf8');
const d=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
test('CSV: quoted comma, escaped quote and multiline content',()=>{assert.deepEqual(d.parseCSV('name,content\r\n"A,B","say ""hi""\nline2"'),[{name:'A,B',content:'say "hi"\nline2'}]);});
test('CSV: BOM and CRLF are handled',()=>assert.deepEqual(d.parseCSV('\uFEFFid,name\r\n1,A\r\n'),[{id:'1',name:'A'}]));
test('CSV export escapes formulas without removing commas or newlines',()=>{const rows=d.parseCSV(d.csvString([{a:'=2+3',b:'A,B\n"C"'}],[{key:'a',label:'a'},{key:'b',label:'b'}]));assert.deepEqual(rows,[{a:"'=2+3",b:'A,B\n"C"'}]);});
test('URL rejects javascript, data, credentials and control characters',()=>{for(const url of ['javascript:alert(1)','data:text/html,<svg>','https://a:b@host/a','https://a.com/\u0000'])assert.equal(d.safeUrl(url),'');});
test('URL accepts HTTP/S and resolves relative resources',()=>assert.equal(d.safeUrl('/image/a','http://127.0.0.1:5030'),'http://127.0.0.1:5030/image/a'));
test('Highlight literal regex characters without compiling user expressions',()=>{const parts=d.highlightParts('<img onerror=1> a+b? [ok]',['a+b?','[ok]']);assert.equal(parts.filter(p=>p.match).length,2);assert.equal(parts.map(p=>p.value).join(''),'<img onerror=1> a+b? [ok]');});
test('Unsafe media remains inert text',()=>assert.equal(d.mediaParts('![图片](javascript:evil)')[0].type,'text'));
test('Multiline legacy messages are not truncated to a single line',()=>{const rows=d.parseChatLogs('A(id) 2026-09-20 10:00:00\nline1\nline2\nB(id2) 2026-09-20 11:00:00\nlast');assert.equal(rows.length,2);assert.equal(rows[0].content,'line1\nline2');});
test('Wrapped JSON chat responses are normalized',()=>{assert.equal(d.parseChatLogs({data:{items:[{sender:'wxid',content:'hello',time:'2026-09-20'}]}})[0].senderId,'wxid');});
test('JSON, CSV and legacy session formats normalize stable IDs',()=>{const s=d.normalizeSession(d.parseList('群名(room@chatroom) 2026-09-20 10:00:00','sessions')[0]);assert.equal(s.id,'room@chatroom');assert.equal(s.kind,'room');});
test('Unknown members are null, zero members stay zero',()=>{assert.equal(d.normalizeRoom({Name:'r'}).members,null);assert.equal(d.normalizeRoom({Name:'r',UserCount:'0'}).members,0);});
test('Unknown dates do not become today',()=>{for(const value of [null,undefined,'','not-a-date'])assert.equal(d.toDate(value),null);});
test('Unix seconds and milliseconds resolve to the same date',()=>assert.equal(d.toDate(1700000000).getTime(),d.toDate(1700000000000).getTime()));
test('Inclusive date ranges contain exactly the requested day count',()=>assert.equal(d.rangeDays(7,new Date(2026,8,23)),'2026-09-17~2026-09-23'));
test('All analysis metrics use the same selected range',()=>{const logs=[{content:'设计',senderId:'a',time:'2026-09-23T12:00:00',talkerId:'r@chatroom',talkerName:'R'},{content:'旧记录',senderId:'b',time:'2026-08-01T13:00:00'}];const a=d.analyze(logs,7,new Date(2026,8,23));assert.equal(a.total,1);assert.equal(a.users,1);assert.equal(a.types.reduce((s,p)=>s+p.value,0),1);assert.equal(a.heat.flat().reduce((s,v)=>s+v,0),1);assert.equal(a.hourly.reduce((s,v)=>s+v,0),1);assert.equal(a.groups[0].value,1);});
test('Empty analysis has finite zeros and no fabricated entries',()=>{const a=d.analyze([],30);assert.equal(a.total,0);assert.equal(a.users,0);assert.equal(a.average,0);assert.equal(a.groups.length,0);assert.equal(a.words.length,0);});
test('Heatmap starts on Monday',()=>{const a=d.analyze([{time:'2026-09-21T12:00:00',content:'hello'}],7,new Date(2026,8,23));assert.equal(a.heat[0][12],1);});
test('Duplicate media uses type+URL identity; size stays unknown',()=>{const logs=[{content:'![图片](/image/a)',time:'2026-09-21'},{content:'![图片](/image/a)',time:'2026-09-22'}];const a=d.extractMedia(logs,'https://example.test');assert.equal(a.length,1);assert.equal(a[0].size,null);});
