// Code generated by scripts/gen_feature_types.py from packages/contracts/feature-catalog.json.
// DO NOT EDIT BY HAND (R42.2: feature-catalog.json is the single source of truth).

export const FEATURES = {
  FEATURE_ARCHIVE_READ: "archive.read",
  FEATURE_ARCHIVE_INGEST: "archive.ingest",
  FEATURE_MEDIA_UPLOAD_IMAGE: "media.upload.image",
  FEATURE_MEDIA_UPLOAD_VIDEO: "media.upload.video",
  FEATURE_MEDIA_UPLOAD_AUDIO: "media.upload.audio",
  FEATURE_MEDIA_UPLOAD_FILE: "media.upload.file",
  FEATURE_MEDIA_PREVIEW: "media.preview",
  FEATURE_MEDIA_TRANSCODE: "media.transcode",
  FEATURE_MEDIA_OCR: "media.ocr",
  FEATURE_MEDIA_TRANSCRIBE: "media.transcribe",
  FEATURE_MEDIA_DOCUMENT_EXTRACT: "media.document_extract",
  FEATURE_CUSTOMER_MANAGE: "customer.manage",
  FEATURE_AI_PROFILE: "ai.profile",
  FEATURE_AI_SUMMARY: "ai.summary",
  FEATURE_ANALYTICS_ADVANCED: "analytics.advanced",
  FEATURE_SEARCH_ADVANCED: "search.advanced",
  FEATURE_MCP_READ: "mcp.read",
  FEATURE_MCP_WRITE: "mcp.write",
  FEATURE_BACKUP_SCHEDULE: "backup.schedule",
  FEATURE_ENTERPRISE_SSO: "enterprise.sso",
  FEATURE_DATA_EXPORT: "data.export",
  FEATURE_QUALITY_MANAGE: "quality.manage",
  FEATURE_OPS_MANAGE: "ops.manage",
};

// 平台表单映射（R42.2）：feature key -> 平台目录展示（name/description/depends_on）。
export const FEATURE_CATALOG = {
  "archive.read": {
    name: "增强聊天工作台",
    description: "增强聊天工作台读取能力。基础历史取回不由商业开关封锁。",
    dependsOn: [],
  },
  "archive.ingest": {
    name: "新聊天采集、同步",
    description: "新聊天采集与同步。多媒体消息元数据保留；原件类型另授予。",
    dependsOn: [],
  },
  "media.upload.image": {
    name: "图片原件同步",
    description: "图片原件同步。",
    dependsOn: ["archive.ingest"],
  },
  "media.upload.video": {
    name: "视频原件同步",
    description: "视频原件同步。",
    dependsOn: ["archive.ingest"],
  },
  "media.upload.audio": {
    name: "语音、音频原件同步",
    description: "语音、音频原件同步；不含转写。",
    dependsOn: ["archive.ingest"],
  },
  "media.upload.file": {
    name: "普通附件同步",
    description: "文档、压缩包等普通附件同步；不允许任意读文件系统。",
    dependsOn: ["archive.ingest"],
  },
  "media.preview": {
    name: "增强预览、缩略图",
    description: "新建增强预览、缩略图。已有安全原件/派生件仍可取回。",
    dependsOn: [],
  },
  "media.transcode": {
    name: "音视频转码",
    description: "新音视频转码；不覆盖原件。",
    dependsOn: ["media.preview"],
  },
  "media.ocr": {
    name: "图片文字识别",
    description: "图片文字识别。外部 OCR 另需外发同意、配置和预算。",
    dependsOn: [],
  },
  "media.transcribe": {
    name: "语音、视频转写",
    description: "语音、视频转写。外部 ASR 另需外发同意、配置和预算。",
    dependsOn: [],
  },
  "media.document_extract": {
    name: "文档正文提取",
    description: "文档正文提取。沙箱处理，不运行宏或脚本。",
    dependsOn: [],
  },
  "customer.manage": {
    name: "客户、标签、备注、跟进写入",
    description: "客户、标签、备注、跟进写入。历史资料按 ACL 保留。",
    dependsOn: [],
  },
  "ai.profile": {
    name: "新建/刷新客户画像",
    description: "新建/刷新客户画像。证据、外发、费用另查。",
    dependsOn: ["customer.manage"],
  },
  "ai.summary": {
    name: "新建/刷新会话摘要",
    description: "新建/刷新会话摘要。既有摘要可受控读取。",
    dependsOn: [],
  },
  "analytics.advanced": {
    name: "高级统计、报表生成",
    description: "高级统计、报表生成。既有报表可取回。",
    dependsOn: [],
  },
  "search.advanced": {
    name: "高级检索",
    description: "高级组合/语义等检索操作。基础准确查询不可假空、故意减速。",
    dependsOn: [],
  },
  "mcp.read": {
    name: "企业 MCP 读工具、资源",
    description: "企业 MCP 读工具、资源。还检查目标业务功能、ACL、Host 外发政策。",
    dependsOn: [],
  },
  "mcp.write": {
    name: "企业 MCP 业务写工具",
    description: "企业 MCP 业务写工具。不含平台发证、SQL 或 Shell。",
    dependsOn: ["mcp.read"],
  },
  "backup.schedule": {
    name: "周期自动备份计划",
    description: "新建周期自动备份计划。必要安全备份、手动取回、隔离恢复属保护通道。",
    dependsOn: [],
  },
  "enterprise.sso": {
    name: "SSO 配置和新会话能力",
    description: "SSO 配置和新会话能力。到期保留安全的应急管理员登录。",
    dependsOn: [],
  },
  "data.export": {
    name: "高级模板、自动化导出",
    description: "高级模板、自动化导出。标准格式的完整数据取回不付费封锁。",
    dependsOn: [],
  },
  "quality.manage": {
    name: "清洗、重解析等高级写操作",
    description: "清洗、重解析等高级写操作。必要安全回滚/修复独立保护。",
    dependsOn: [],
  },
  "ops.manage": {
    name: "高级批量运维",
    description: "高级批量运维。心跳、健康、取消、基础审计、许可修复不可关闭。",
    dependsOn: [],
  },
};
